### ISSUE TITLE
@nowarn annotations behavior change between 0.5.0 and 0.5.1

### ISSUE THREAD

**Issue by jacbop** [typelevel/sbt-tpolecat#210]
In version 0.5.0, we were able to suppress unused value warnings in scalacheck tests like so:
```
package com.test

import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.should.Matchers
import scala.annotation.nowarn

@nowarn("msg=unused value of type org.scalatest.Assertion")
class MainSpec extends AnyFreeSpec with Matchers {
  "unused value warnings" in {
    "3".toInt shouldBe 3
    "4".toInt shouldBe 4
  }
}
```

This complies and runs with 0.5.0 of the plugin, but under version 0.5.1 we see the following compiler error:
```
➜  test [error] -- [E176] Potential Issue Error: /Users/twilberding/test/src/test/scala/MainSpec.scala:10:4
[error] 10 |    "3".toInt shouldBe 3
[error]    |    ^^^^^^^^^^^^^^^^^^^^
[error]    |    unused value of type org.scalatest.Assertion
[error] one error found
[error] (Test / compileIncremental) Compilation failed
```

I see from the README that we can disable this in built.sbt with `Test / tpolecatExcludeOptions += ScalacOptions.warnNonUnitStatement`

But we have many projects that are suppressing on a per file basis via annotations. 
Is this a regression issue or a desired functionality change between 0.5.0 and 0.5.1?

**Comment by TonioGela** [comment]
> Is this a regression issue or a desired functionality change between 0.5.0 and 0.5.1?

This flag got in by default when updating `typelevel/scalac-options` and I'm prone to say that is a desired functionality, as in general, it warns you when you forget unused stuff, i.e.

```scala
//> using scala 3.4.1
//> using toolkit typelevel::latest
//> using option -Wnonunit-statement

import cats.effect.*

object Main extends IOApp.Simple:
  def run: IO[Unit] =
    IO.pure("discarded") // <-- you'll get a warn here
    IO.println("foo") *> IO.println("bar")
```

As per your case, I'll try to reproduce it with sbt, as with scala-cli it doesn't appear to be faulty:

```scala
//> using scala 3.3.3
//> using dep org.scalatest::scalatest::3.2.18
//> using option -Wnonunit-statement, -Wunused:nowarn

import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.should.Matchers
import scala.annotation.nowarn

@nowarn("msg=unused value of type org\\.scalatest\\.Assertion")
class MainSpec extends AnyFreeSpec with Matchers:
  "unused value warnings" in {
    "3".toInt shouldBe 3
    "4".toInt shouldBe 4
  }
```

A thing to bear in mind is that the syntax for nowarn is `@nowarn("msg=<regex>")` so theoretically you might want to escape the dots if you're planning to match against the exact string (i.e. `@nowarn("msg=unused value of type org\\.scalatest\\.Assertion")`)
Also, I suggest you using `-Wunused:nowarn` for debug, so that you might get a warn even when a nowarn gets unused (maybe because the regex isn't matching)

**Comment by TonioGela** [comment]
As @Daenyth made me notice, this is probably related to a 3.3.x bug: https://github.com/scala/scala3/issues/18804.
Apparently updating to 3.4.1 seems to be the only fix apart for: https://github.com/typelevel/sbt-tpolecat/issues/134#issuecomment-1817782036.
See further details here: https://gist.github.com/Daenyth/a008964c61b1740974767b833064cc5e
